create table IF NOT EXISTS USERS (
    USER_ID                   bigint generated by default as identity,
    USER_NAME        varchar(255),
    USER_REAL_NAME       varchar(255),
    USER_PASSWORD          varchar(255),
    USER_TYPE_ID       numeric,
    USER_STATUS bool,
    EMAIL_CONTACT       varchar(255),
    PRIMARY KEY (USER_ID)
    );

CREATE TABLE IF NOT EXISTS USER_TYPE (
  USER_TYPE_ID bigint generated by default as identity,
      USER_TYPE_NAME varchar(128),
  PRIMARY KEY (USER_TYPE_ID)
);

CREATE TABLE IF NOT EXISTS ALERT_INBOX (
  ALERT_ID generated by default as identity,
  PROPERTY_ID bigint bigint,
  USER_ID bigint,
  ALERT_MESSAGE varchar(255),
  SHOW_ALERT bool,
  ALERT_TYPE bigint,
  CREATED_AT timestamptz(0),
  UPDATED_AT timestamptz(0),
  PRIMARY KEY (ALERTS_ID)
);

CREATE TABLE IF NOT EXISTS PROPERTY (
  PROPERTY_ID bigint generated by default as identity,
  PROPERTY_ADDRESS  VARCHAR(255),
  PROPERTY_PRICE  float4,
  LAST_PROPERTY_PRICE float4,
  USER_ID numeric,
  PROPERTY_STATUS_ID NUMERIC,
  PROPERTY_OWNER_NAME VARCHAR(255),
  PROPERTY_OWNER_EMAIL VARCHAR(255),
  PROPERTY_OWNER_TEL VARCHAR(255),
  IS_FINANCED boolean,
  IS_OWNER_NAMED boolean,
  IS_NEGOTIABLE boolean,
  CREATED_AT timestamptz(0),
  UPDATED_AT timestamptz(0),
  USER_EDITED_ID numeric,
  PICTURE_1_X64 text,
  PICTURE_2_X64 text,
  PICTURE_3_X64 text,
  PICTURE_4_X64 text,
  PICTURE_5_X64 text,
  PRIMARY KEY (PROPERTY_ID)
);

CREATE TABLE IF NOT EXISTS PROPERTY_STATUS (
  PROPERTY_STATUS_ID bigint generated by default as identity,
  PROPERTY_STATUS_NAME VARCHAR(255),
  PRIMARY KEY (PROPERTY_STATUS_ID)
);

CREATE TABLE IF NOT EXISTS ALERT_TYPES (
  ALERT_TYPE_ID bigint generated by default as identity,
  ALERT_NAME VARCHAR(255),
  PRIMARY KEY (ALERT_TYPE_ID)
);

insert into ALERT_TYPES(ALERT_TYPE_ID, ALERT_NAME) values (1,'Solicitacao de propriedade') ON CONFLICT (ALERT_TYPE_ID)  DO NOTHING;
insert into ALERT_TYPES(ALERT_TYPE_ID, ALERT_NAME) values (2,'Criação de Usuário')ON CONFLICT (ALERT_TYPE_ID)  DO NOTHING;
insert into ALERT_TYPES(ALERT_TYPE_ID, ALERT_NAME) values (3,'Dias sem atualizacao')ON CONFLICT (ALERT_TYPE_ID)  DO NOTHING;
insert into ALERT_TYPES(ALERT_TYPE_ID, ALERT_NAME) values (4,'Criação de Propriedade')ON CONFLICT (ALERT_TYPE_ID)  DO NOTHING;

insert into USER_TYPE (USER_TYPE_ID, USER_TYPE_NAME) values (1,'User')ON CONFLICT (USER_TYPE_ID)  DO NOTHING;
insert into USER_TYPE (USER_TYPE_ID, USER_TYPE_NAME) values (2,'Owner')ON CONFLICT (USER_TYPE_ID)  DO NOTHING;

insert into PROPERTY_STATUS (PROPERTY_STATUS_ID, PROPERTY_STATUS_NAME) values (1,'Livre')ON CONFLICT (PROPERTY_STATUS_ID)  DO NOTHING;
insert into PROPERTY_STATUS (PROPERTY_STATUS_ID, PROPERTY_STATUS_NAME) values (2,'Alugado')ON CONFLICT (PROPERTY_STATUS_ID)  DO NOTHING;
insert into PROPERTY_STATUS (PROPERTY_STATUS_ID, PROPERTY_STATUS_NAME) values (3,'Vendido')ON CONFLICT (PROPERTY_STATUS_ID)  DO NOTHING;

CREATE or replace VIEW ALERT_INFO AS
SELECT
ai.ALERT_ID,
ai.USER_ID,
ai.PROPERTY_ID,
ai.ALERT_MESSAGE,
ai.SHOW_ALERT,
ai.alert_type,
ap.ALERT_NAME,
ai.updated_At,
u.USER_REAL_NAME,
u.EMAIL_CONTACT,
p.PROPERTY_ADDRESS
FROM ALERT_INBOX ai
join USERS u on ai.USER_ID = u.user_id
LEFT join PROPERTY p on ai.property_id = p.property_id
join ALERT_TYPES ap on ai.alert_type = ap.alert_type_id
where SHOW_ALERT = true;
